# Generated by Django 2.2 on 2019-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20190414_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='api_key',
            field=models.CharField(default='TxdprLXXy4', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='secret_key',
            field=models.CharField(default='6yTwNnUTmF', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='token',
            field=models.CharField(default='Bx11djAKvGQeXqsn', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='token_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
