# Generated by Django 2.2 on 2019-04-15 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20190414_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='restore_token',
            field=models.CharField(default='xR6nwN3NqwXRpLjQ', max_length=32),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='restore_token_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 19, 58, 10, 55360)),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='api_key',
            field=models.CharField(default='RvD9ZZG9sP', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='secret_key',
            field=models.CharField(default='YwfAh2pyuv', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='token',
            field=models.CharField(default='yPZ4tWBRUrPsSeOz', max_length=32),
        ),
    ]
