# Generated by Django 2.2 on 2019-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20190520_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='api_key',
            field=models.CharField(default='jyzt5G80Jn', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='restore_token',
            field=models.CharField(default='S61YikKisqG52LYf', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='secret_key',
            field=models.CharField(default='PQrbod96QM', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='token',
            field=models.CharField(default='mR553atXBwaT5s8g', max_length=32),
        ),
    ]
