# Generated by Django 2.2 on 2019-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20190520_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='api_key',
            field=models.CharField(default='RkRhdyzqDP', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='restore_token',
            field=models.CharField(default='TxgJbEdKH34OdJw4', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='secret_key',
            field=models.CharField(default='M52Qcapbhd', max_length=32),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='token',
            field=models.CharField(default='VCaStwcPq9ppsuxi', max_length=32),
        ),
    ]
