# Generated by Django 2.2 on 2019-04-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermocontrollerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termocontroller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('target_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('KWatts', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('time_get_data', models.DateTimeField(auto_now=True)),
                ('model_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Device.TermocontrollerName')),
            ],
        ),
    ]
