# Generated by Django 2.2 on 2019-04-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_termocontroller_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocontroller',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
