# Generated by Django 2.2 on 2019-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_termocontroller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocontroller',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
