# Generated by Django 2.2 on 2019-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_termocontroller_firmware_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocontroller',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
