# Generated by Django 2.2 on 2019-05-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_auto_20190520_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermocontStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.Termocontroller')),
            ],
        ),
    ]
