# Generated by Django 2.2 on 2019-05-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0006_termocontstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='termocontroller',
            name='firmware_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Device.TermocontrollerFirmware'),
        ),
    ]
